jupiter:
    radius: 71492.0e3 # m
    distance: 5.2 # AU
    albedo: 0.52 
    temperature: 121 # K
    peak_wavelength: 0.0042 # m
    distance_at_perigee: 740.522e9 # m
    distance_at_apogee: 816.618e9 # m
earth:
    distance: 1 # AU
    albedo: 0.3
    temperature: 250.15 # K
    peak_wavelength: 0.01005 # m
moon:
    distance_to_earth: 3.844e8 # m
    radius: 1.737e6 # m
    albedo: 0.11
    distance: 0.999985879 # AU
pluto:
    radius: 1150000 # m
    distance_at_perigee: 4.4e12 # m
    distance_at_apogee: 7.3e12 # m
sodium_vapor_lamp:
    lambda_1: 5890.0e-10 # m
    lambda_2: 5896.0e-10 # m
    total_power: 35 # W
